### ISSUE TITLE
AlonsoLevels Bug on reload

### ISSUE THREAD

**Issue by king-glitch** [AlonsoAliaga/AlonsoLevels#1]
**Describe the bug**
AlonsoLevels Bug on reload 

**To Reproduce**
1. when type /alonsolevels reload
2. it shows An internal error occurred while...

**Expected behavior**
config reload without bug

**Screenshots**
<img width="517" alt="Screen Shot 2563-09-04 at 16 32 36" src="https://user-images.githubusercontent.com/58404132/92224615-42391e00-eecc-11ea-8063-60859355fbcf.png">
<img width="1336" alt="Screen Shot 2563-09-04 at 16 33 38" src="https://user-images.githubusercontent.com/58404132/92224712-6432a080-eecc-11ea-8637-70b7367423c2.png">

**Important (please complete the following information):**
 - Java version: [System Info: Java 1.8 (Java HotSpot(TM) 64-Bit Server VM 25.251-b08) Host: Windows Server 2019 10.0 (amd64)]
 - Plugin version: [e.g.  v0.2-BETA]
 - Server version [Use /icanhasbukkit in console]
This server is running SSSpigot version SSSpigot-1.16.2-20200903-8eee073 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Additional context**

**Comment by AlonsoAliaga** [comment]
Make sure you don't remove any line from config file.
I made "/alonsolevels reload" and command works perfectly fine, try reinstalling the plugin from zero and using the command.
If problem persists, let me know.

I can't reproduce the error

![79b036b6df70b68fc5b6fb6d8a380fcb](https://user-images.githubusercontent.com/36780081/92251354-53653900-ee92-11ea-9738-c50ada373cea.png)

**Comment by king-glitch** [comment]
I have no idea. after I tried to delete the hold plugin folder. and restarted the server, let it generates the file. The errors where change to this after trying to reload. 
<img width="1346" alt="Screen Shot 2563-09-05 at 03 19 17" src="https://user-images.githubusercontent.com/58404132/92281962-eb146700-ef26-11ea-806a-166767000420.png">

**Comment by AlonsoAliaga** [comment]
"the hold plugin"? Please, try with a fresh install. If it works, modify the config and post here **all modifications** made.
I tried to replicate the error, but works for me. No problem with "/alonsolevels reload" command.
