### ISSUE TITLE
HikariCP does not work but MySQL driver does

### ISSUE THREAD

**Issue by dollannn** [AlonsoAliaga/AlonsoLevels#10]
**Describe the bug**
The title says it all

**To Reproduce**
1. Enable MySQL which uses the HikariCP driver

**Expected behavior**
It working

**Screenshots**
*Disconnected screen*

**Important (please complete the following information):**
 - Java version: 18
 - Plugin version: 2.2.4-BETA
 - Server version Current: git-Purpur-1712 (MC: 1.19)*

**Additional context**

**Comment by AlonsoAliaga** [comment]
Use "IWantMySQL" instead of "MySQL" and set Additional-url to "?useSSL=false"

**Comment by dollannn** [comment]
Yes that is what I did to resolve the issue hence the title, but I still reported the bug for your knowledge

**Comment by AlonsoAliaga** [comment]
You must have
useSSL: "false"
in HikariCP options to prevent that issue afaik
