### ISSUE TITLE
DataBase

### ISSUE THREAD

**Issue by thenodin** [AlonsoAliaga/AlonsoLevels#11]
There are two servers on Velocity. MySQL is running on one server, and SQLite is loading on another. The configurations are the same. Also, after restarting the server with the SQLite error, "Server: Lobby" is not renamed to my name.

(Fail) (Another server)
![image](https://user-images.githubusercontent.com/77510003/230722442-f5a46580-7d16-4a78-a530-f5acce4a5da8.png)

(Success) (Lobby)
![image](https://user-images.githubusercontent.com/77510003/230722478-db52ce99-7b83-4ff0-9186-78d6578861c4.png)

Java 17
2.2.1-BETA
Dionysus 1.12.2

**Comment by AlonsoAliaga** [comment]
I need full console log of both in a bin to be able to figure out the issue. If you wan you can join our discord server on https://alonsoaliaga.com/discord and share them in a ticket

**Comment by thenodin** [comment]
First file - Lobby
Second - Another
[latest.log](https://github.com/AlonsoAliaga/AlonsoLevels/files/11183513/latest.log)
[latest (1).log](https://github.com/AlonsoAliaga/AlonsoLevels/files/11183514/latest.1.log)

**Comment by thenodin** [comment]
I found a solution to the problem. There were two files Alonso Levels and Levels (renamed AlonsoLevels)
