### ISSUE TITLE
The plugin does not work at all, this probably happened when I installed java 17

### ISSUE THREAD

**Issue by RangeBanenge** [AlonsoAliaga/AlonsoLevels#12]
**Expected behavior**

**Screenshots**

**Important (please complete the following information):**
 - Java version: [17]
 - Plugin version: [ALPHA-2.2.4]
 - Server version [Use /icanhasbukkit in console]
 - paper 1.12.2
 - [AIONSOLevels] Failed to load Javascript (1).
[AlonsoLevels] Failed to load 'JavaScript' (2).
==
[AlonsoLevels] Failed to load 'graal.js' (1).
==
[AlonsoLevels] Failed to load 'graal.js' (2). ==
[AlonsoLevels] Failed to load 'js' (1).
==
[AlonsoLevels] Failed to load 'js' (2).
==
[AlonsoLevels] Failed to load 'nashorn' (1).
== [AlonsoLevels] Failed to load 'nashorn' (2).
==
[AlonsoLevels] Backup alternatives failed to start. Your system doesn't have requirements
[AlonsoLevels] to run JavaScript expressions which is required for this plugin.
[AlonsoLevels] As first alternative, you can try installing the plugin called MomoJS. MomoJS
[AlonsoLevels] will add javascript engine again to your server and make this plugin work.
[AlonsoLevels] Download latest version here: https://alonsoaliaga.com/MomoJS
[AlonsoLevels] As second alternative, you can try installing the plugin called JSEngine. JSEngine
[AlonsoLevels] is a wrapper for Nashron JavaScript engine that allows plugins to access [AlonsoLevels] JavaScript engine even if the system doesn't have it. This is
[AlonsoLevels] just an alternative and might not work in all cases. Download the plugin
[AlonsoLevels] directly from this link: https://alonsoaliaga.com/JSEngine
[
AlonsoLevels] Once downloaded, copy to plugin folder and restart your server.
[AlonsoLevels] If you still want to use the plugin without JSEngine you will have to edit [AlonsoLevels] levels.yml file and disable Experience formula option in config.yml file.
The plugin does not work at all, this probably happened when I installed java 17

**Comment by AlonsoAliaga** [comment]
Solved in Discord by downloading the suggested plugins.
