### ISSUE TITLE
[AlonsoLevels 2.3.2-BETA]1.8.8 server cannot connect to MySQL

### ISSUE THREAD

**Issue by BBDL233** [AlonsoAliaga/AlonsoLevels#16]
Running v2.3.2-BETA (v1_8)
Server CraftBukkit vgit-PaperSpigot-445 (MC: 1.8.8)
first,i use java 8 run server
In config.yml,I configured it this way
![image](https://github.com/AlonsoAliaga/AlonsoLevels/assets/99265367/89c33373-12f0-4bba-a6a2-5d8e06740de0)
I am very certain that I entered correctly because in other plugins, it can link to MySQL normally。
but
[1.txt](https://github.com/AlonsoAliaga/AlonsoLevels/files/14210642/1.txt)
This is the information provided to me by the server when loading the plugin.
But I can link MySQL normally using this version of the plugin on the 1.20.4 server, and I ensure that their config.yml is the same!
I think it's possible that my Java version is too old, so I ran the server using Java17。
I will run the server again.I have achieved such results
[2.txt](https://github.com/AlonsoAliaga/AlonsoLevels/files/14210713/2.txt)
I didn't intentionally use spaces to separate information. For me, running Java 17 on 1.8 is like this.
The result is still not successful in linking.
So I saw this: 
![image](https://github.com/AlonsoAliaga/AlonsoLevels/assets/99265367/742fadf8-007f-452d-96e0-31f1dc0fe697)
I don't think I have installed MomoJS or JSEngine.
So I added MomoJS and JSEngine plugins
Run the server again
[3.txt](https://github.com/AlonsoAliaga/AlonsoLevels/files/14210769/3.txt)
Still not successfully linked
I am confident that I have correctly installed the NBTAPI, MomoJS, and JSEngine plugins
I went to seek help from AI
[AI say.txt](https://github.com/AlonsoAliaga/AlonsoLevels/files/14210802/AI.say.txt)
Okay, I don't know how I should fix it.
But I feel like it's a coding issue
After all, higher versions can be linked correctly
So I started the server like this
---
"F:\\Java\bin\java.exe" -Dfile.encoding=UTF-8   -Xms0M -Xmx1024M -jar paper-1.8.8-445.jar nogui
---
![image](https://github.com/AlonsoAliaga/AlonsoLevels/assets/99265367/7a9dd1de-25fb-4268-9e3f-94f2753a828e)
[4.txt](https://github.com/AlonsoAliaga/AlonsoLevels/files/14210873/4.txt)
Suddenly popping up so many things startled me
Not only is MySQL not linked, but other plugins have garbled code. Fortunately, I have an save
At this point, I ran the server again using Java8...
[5.txt](https://github.com/AlonsoAliaga/AlonsoLevels/files/14210926/5.txt)
My attempt may be a bit funny.Is there a problem with the configuration of config.yml?
![image](https://github.com/AlonsoAliaga/AlonsoLevels/assets/99265367/34d37ddc-5def-4e28-91cf-d5d163516995)
So I made this attempt
Running v2.3.2-BETA (v1_8)
Server CraftBukkit vgit-PaperSpigot-445 (MC: 1.8.8)
use java 8 run server
[6.txt](https://github.com/AlonsoAliaga/AlonsoLevels/files/14210964/6.txt)
also
![image](https://github.com/AlonsoAliaga/AlonsoLevels/assets/99265367/e01bfe68-bf78-4017-827f-00189e0c8bf0)
get
[7.txt](https://github.com/AlonsoAliaga/AlonsoLevels/files/14210983/7.txt)
It looks like the problems are all similar, I can't see any difference, as long as we record everything.
---
Finally, I can assure you that there are no configuration issues with my config.yml and other files, only issues with linking MySQL. However, I can correctly link MySQL on a 1.20.4 server running on Java 17 using the same file
like this
![image](https://github.com/AlonsoAliaga/AlonsoLevels/assets/99265367/05941dc4-6200-45e9-84ac-e855f257fd2b)
![image](https://github.com/AlonsoAliaga/AlonsoLevels/assets/99265367/a527fe3b-93a7-4f65-b83b-754cd9ca11b0)
Can generate the database correctly
![image](https://github.com/AlonsoAliaga/AlonsoLevels/assets/99265367/0a7b551b-c854-460a-90ed-63dc0f87a3bb)
----
I'm not sure if it's a plugin issue or my problem, I've tried many times already
I want to find a solution

**Comment by BBDL233** [comment]
new
![image](https://github.com/AlonsoAliaga/AlonsoLevels/assets/99265367/0fb9982c-cb86-483c-ac14-3b72424d96ac)
![image](https://github.com/AlonsoAliaga/AlonsoLevels/assets/99265367/5521f5a2-c9b9-4fb6-a4bc-9d2999340d54)

**Comment by AlonsoAliaga** [comment]
This is weird, I don't think i saw a notification about this issue in my gmail. Sorry for the delay, setting database type to "IWantMySQL" and setting additional-url to "?useSSL=false" fixes the issue. Let me know hiw it works.
Additionally, read the red message and set the option to true

**Comment by BBDL233** [comment]
Can you provide the correct file that can be linked to MySQL?

How should I contact you

**Comment by AlonsoAliaga** [comment]
Correct file of? Please just edit what i mentioned above, i'm on mobile

**Comment by BBDL233** [comment]
Still unable to link

![image](https://github.com/AlonsoAliaga/AlonsoLevels/assets/99265367/431252cc-88e8-46f3-a0e7-d1902a1a8286)
![image](https://github.com/AlonsoAliaga/AlonsoLevels/assets/99265367/87f24993-6a79-499f-8e87-157106ecaf0c)

**Comment by AlonsoAliaga** [comment]
Database type to "IWantMySQL" like that

**Comment by BBDL233** [comment]
Still unable to link
![image](https://github.com/AlonsoAliaga/AlonsoLevels/assets/99265367/c97f99e6-f0a1-4c48-90dc-400a0bcd3f73)

![image](https://github.com/AlonsoAliaga/AlonsoLevels/assets/99265367/4ebbc58b-629c-4e5f-9022-a2ee31c1e8af)

**Comment by AlonsoAliaga** [comment]
I just noticed you are trying to use 1.8.8, mmm
Additional-url:  "?useSSL=false&characterEncoding=utf8"

**Comment by BBDL233** [comment]
Problem solved
So should i always maintain the Database type to "IWantMySQL"?

**Comment by AlonsoAliaga** [comment]
Yes, in your case, keep the IWantMySQL, it will use directly MySQL and shouldn't give any problems

**Comment by BBDL233** [comment]
I have discovered a new issue where Experience bar does not load. Only when I enter/level reload to load it once, when I re-join the server, it becomes the default Experience bar
![image](https://github.com/AlonsoAliaga/AlonsoLevels/assets/99265367/31bf3e3b-c02e-4bb7-95fa-090c0e1f598e)
Rejoin the server
![image](https://github.com/AlonsoAliaga/AlonsoLevels/assets/99265367/961bd4ff-6be2-4116-9ab7-180ab96522ec)
reload the plugin
![image](https://github.com/AlonsoAliaga/AlonsoLevels/assets/99265367/7bdb8f11-bde0-4e4d-a956-6691edf8e41f)

**Comment by AlonsoAliaga** [comment]
That's the intended behavior, only Pro version has an opption to resend the experience bar every X seconds to make sure it's displayed in the experience bar. In free version it's send only on join (and world change iirc) but as it's send only there, any packet that updates player data will refresh the experience bar back to default one.
You can use ConditionalEvents to send the exp bar every X seconds if you want, but Free version doesnt do that

**Comment by BBDL233** [comment]
What I mean is that he doesn't update at all, except for using/level reload

**Comment by AlonsoAliaga** [comment]
I'll take a look later, however, as mentioned above, is most likely that the experience bar is reverted to the original one because of a packet being sent, i'll let you know when i make sure its sent on join

**Comment by BBDL233** [comment]
Simply say, the plugin is working properly and MySQL data can also be synchronized, but the Experience bar is not working
(paper 1.8.8)

**Comment by AlonsoAliaga** [comment]
Put? As description?

**Comment by BBDL233** [comment]
So how to solve it

**Comment by AlonsoAliaga** [comment]
As i said above, i'll take a look when i can do it to make sure its sent on join. I'm at a concert right now, there isnt too much i can do right now tbh

**Comment by BBDL233** [comment]
https://github.com/AlonsoAliaga/AlonsoLevels/issues/17
