### ISSUE TITLE
After linking to MySQL, the Experience bar is not working

### ISSUE THREAD

**Issue by BBDL233** [AlonsoAliaga/AlonsoLevels#17]
**Describe the bug**
After linking to MySQL, the Experience bar is not working

**To Reproduce**
1.download AlonsoLevels-v2.3.2-BETA.jar Put it in plugins
2.download NBTAPI.jar Put it in plugins
3.run paper 1.8.8 
4.set config.yml:
![image](https://github.com/AlonsoAliaga/AlonsoLevels/assets/99265367/e5200474-a3df-41fb-8b60-5cfbfa4f9864)
5.reload plugin

**Expected behavior**
He should be displaying it normally

**Screenshots**
What I see is the Default Experience bar (paper 1.8.8)
![image](https://github.com/AlonsoAliaga/AlonsoLevels/assets/99265367/0d6a00c9-e1d4-4cdb-92cf-bcc741d4fc04)
Normally, it should be like this (paper 1.20.4)
![image](https://github.com/AlonsoAliaga/AlonsoLevels/assets/99265367/c756bd82-242e-4cb5-9f46-6ed4865f3f46)

**Important (please complete the following information):**
 - Java version: 8
 - Plugin version: paper 1.8.8
 - Server version:
 - This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
 - Error obtaining version information
 - 
![image](https://github.com/AlonsoAliaga/AlonsoLevels/assets/99265367/26330eda-90a4-4468-a574-6e44ffb043d3)

**Additional context**
none

**Comment by AlonsoAliaga** [comment]
I've made a dev build for you to test, join us on https://alonsoaliaga.com/discord open a ticket or DM me so I can send it

**Comment by BBDL233** [comment]
When I joined your Discord server, I couldn't pass the robot verification due to Internet issues. You can add me as a discord friend. ID: BBDL233

**Comment by AlonsoAliaga** [comment]
Solved in dev builds, pending to be released
