### ISSUE TITLE
Ssl Mys2ql

### ISSUE THREAD

**Issue by Anonymo99** [AlonsoAliaga/AlonsoLevels#2]
**Describe the bug**
SSL Mysql

**To Reproduce**
Start a server with the plugin connected to a database Mysql

**Screenshots**
https://pastebin.com/nmy1GRLj

**Important (please complete the following information):**
 - Java version: 1.8
 - Plugin version: 1.1-BETA
- Version 1.16.1 PaperSpigot

**Comment by AlonsoAliaga** [comment]
A fix has been implemented, let me know if it still occurs with 1.2-BETA
