### ISSUE TITLE
Engine to parse formula couldn't be found

### ISSUE THREAD

**Issue by jnijland** [AlonsoAliaga/AlonsoLevels#3]
**Describe the bug**
With the latest update, when starting the server, the following error is given in the console: 
```Engine to parse formula couldn't be found```
After this, the plugin disables. I had no problems running the previous version.

**To Reproduce**
1. Upload the latest version of alonsolevels to your plugin folder.
2. Start the server.

**Expected behavior**
The plugin enabling 😄 

**Screenshots**
![image](https://user-images.githubusercontent.com/9889834/95581914-1a445980-0a3a-11eb-810d-0bde4fbcf83f.png)

**Important (please complete the following information):**
 - Java version: 8
 - Plugin version: v1.3_beta
 - Server version: Tuinity 1.15.2

**Additional context**
I also tried it with regular Spigot. Server is ran via Pterodactyl panel. I didn't receive this error previously, the error is pretty clear, but it would be great if some suggestions are made on how to fix 👍

**Comment by AlonsoAliaga** [comment]
Hello, you said it was working correctly with the previous version? You mean 1.2-BETA? Same machine, PC, hosting? Please join my discord server https://discord.gg/DEDaQhs so I can ask you questions faster, I'll take a look later, I'm a bit busy with classes today

**Comment by AlonsoAliaga** [comment]
Keep in mind I'm waiting you in my discord server. I want to release an update but I need to look into your issue first so it can be fixed before the new release

**Comment by AlonsoAliaga** [comment]
Issue fixed in 1.4-BETA (Pending to release in some minutes)
