### ISSUE TITLE
Some performance problems

### ISSUE THREAD

**Issue by myavuzokumus** [AlonsoAliaga/AlonsoLevels#4]
**Describe the bug**
![image](https://user-images.githubusercontent.com/47111280/101275368-1cb2fd80-37b6-11eb-81ff-2de097584a28.png)

 - Java version: AdoptJDK 11 Hotspot
 - Plugin version: 1.7-BETA
 - Server version
![image](https://user-images.githubusercontent.com/47111280/101275379-32282780-37b6-11eb-8d69-e9992662c741.png)

**Comment by AlonsoAliaga** [comment]
Issue solved, fixed in 1.8-BETA (Pending to release in some hours)
