### ISSUE TITLE
Plugin disabling but all configs valid

### ISSUE THREAD

**Issue by swagmobo** [AlonsoAliaga/AlonsoLevels#5]
I installed the plugin and it loaded perfectly and everything worked, but after I edited the configs it was disabled. I validated them all, it said they are all valid, in the levels.yml file, it said don't use numbers above the 32 bit integer limit, and I haven't. I can't seem to find the part where the plugin tried to load in the server console/logs.

I am completely unsure why this happens
![Screenshot (151)](https://user-images.githubusercontent.com/92309982/137630174-05abfdc1-df80-481b-974e-a545d168c2cc.png)

**Comment by AlonsoAliaga** [comment]
Hello, the plugin doesn't disable by itself for no reason. I can tell you that.
Send the full console log in a bin so I can take a look

Also, please join our server so we can talk faster on https://alonsoaliaga.com/discord
