### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ProtoGhost** [AlonsoAliaga/AlonsoLevels#9]
getting this error
using CraftBukkit version git-Spigot-21fe707-741a1bd (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

https://pastebin.com/iJiJWiiH

**Comment by AlonsoAliaga** [comment]
Disable the experience bar feature, it's not working for some reason

Edit 15/01/2024: Should be fixed in latest versions.
